修改persistList为LRUCache
Enraged-Dun-Cookie-Development-Team/cookie-fetcher-core pull request #1
Opened 2024-09-24 19:21 UTC by Bosheng0422

修改原本为String[] 的cookieIdCacheListForPersist 为LRUCache

2024-09-25 00:40 UTC, phidiaLam requested changes

2024-09-25 00:40 UTC, phidiaLam commented on src/datasource/DataSourceCache.ts
> +    }
这个不用留着了

2024-09-25 00:40 UTC, phidiaLam commented on src/datasource/DataSource.ts
> +        this.cookieIdCacheListForPersist?.listAccess(newCookieIds);
这边应该是扔当前蹲到的所有饼，不是单独新饼

2024-09-27 07:23 UTC, Yun-Shan approved these changes

2024-09-27 15:16 UTC, merged